const SEARCH_VALUE_CHANGED = 'SEARCH_VALUE_CHANGED'
const MEDICINE_ADDED = 'MEDICINE_ADDED'
const REQUEST_SEARCH = 'REQUEST_SEARCH'
const RECEIVE_RESULTS = 'RECEIVE_RESULTS'
export {
  SEARCH_VALUE_CHANGED,
  MEDICINE_ADDED,
  REQUEST_SEARCH,
  RECEIVE_RESULTS
}
