const SEARCH_VALUE_CHANGED = 'SEARCH_VALUE_CHANGED'
const REQUEST_SEARCH = 'REQUEST_SEARCH'
const RECEIVE_RESULTS = 'RECEIVE_RESULTS'
export {
  SEARCH_VALUE_CHANGED,
  REQUEST_SEARCH,
  RECEIVE_RESULTS
}
